version: '3'
services:
    webserver:
        build: ./webserver
        ports:
            - "5000:5000"
        volumes:
            - ./webserver:/code/webserver
        environment:
            FLASK_ENV: development
        env_file:
            - .env

    bot:
        build: ./bot
        container_name: 'bot'
        ports:
            - "5001:5001"
        volumes:
            - ./bot:/code/bot
        env_file:
            - .env

    redis:
        image: "redis:alpine"

    localtunnel_web:
        image: efrecon/localtunnel
        links:
          - webserver
        command:
          --local-host webserver --port 5000 --subdomain your-sub-domain-for-webserver-here # ! CHANGE SUBDOMAIN HERE!
        restart: on-failure # Will restart if there's an internal problem to the server hosting localtunnel service

    localtunnel_bot:
        image: efrecon/localtunnel
        links:
          - bot
        command:
          --local-host bot --port 5001 --subdomain your-sub-domain-for-bot-here # ! CHANGE SUBDOMAIN HERE!
        restart: on-failure # Will restart if there's an internal problem to the server hosting localtunnel service
