appName: SpotSurveyBot

spotify:
    url:
        loginURL: 'https://accounts.spotify.com/authorize?'
        tokenURL: 'https://accounts.spotify.com/api/token'
        userURL: 'https://api.spotify.com/v1/me'

        redirectURL: '' # ! Fill this with localtunnel-generated URL for webserver (with /callback) (see tutorial)

        playlist:
            userURL: 'https://api.spotify.com/v1/users/{user_id}/playlists'
            currentUserURL: 'https://api.spotify.com/v1/me/playlists'
            tracksURL: 'https://api.spotify.com/v1/playlists/{playlist_id}/tracks'
            followedURL: 'https://api.spotify.com/v1/playlists/{playlist_id}/followers'

        recommendationURL: 'https://api.spotify.com/v1/recommendations'
        topURL: 'https://api.spotify.com/v1/me/top/{type}'

    acessScope: 'user-read-private playlist-modify-private playlist-read-private user-top-read user-read-recently-played'
    playlistName: "SpotSurveyBot's playlist"
    playlistDescription: "A playlists created by the Telegram Bot SpotSurveyBot"

telegram:
    webhookURL: '' # ! Fill this with localtunnel-generated URL for bot (see tutorial)

