appName: SpotSurveyBot

spotify:
    url:
        loginURL: 'https://accounts.spotify.com/authorize?'
        tokenURL: 'https://accounts.spotify.com/api/token'
        userURL: 'https://api.spotify.com/v1/me'
        redirectURL: 'https://spot-survey-server5.loca.lt/callback' # ! Needs to be registered on Spotify API Dashboard!
        playlist:
            userURL: 'https://api.spotify.com/v1/users/{user_id}/playlists'
            currentUserURL: 'https://api.spotify.com/v1/me/playlists'
            tracksURL: 'https://api.spotify.com/v1/playlists/{playlist_id}/tracks'

    acessScope: 'user-read-private playlist-modify-private playlist-read-private user-top-read user-read-recently-played'
    playlistName: "SpotSurveyBot's playlist"
    playlistDescription: "A playlists created by the Telegram Bot SpotSurveyBot"

telegram:
    webhookURL: 'https://spot-survey-bot6.loca.lt/'

